### ISSUE TITLE
Security Data Issues Secrets in clear text

### ISSUE THREAD

**Issue by shaybenb** [jolle/laudatur-server#1]
Hi,<br><br>url : https://github.com/jolle/laudatur-server/blob/23480dcd63e05b27d3d079b54fbef0b97bb77043/app.yaml <br><br>You have commit that need to remove from the github history<br>attacker can see it and use it ...<br><br>encrypt your secrets !!!!<br><br>Our Bug Help you to be more Secure and protect your data ?<br>Buy me a coffee (or more likely a beer)<br>https://www.paypal.com/paypalme/bugbounty1/150USD<br>https://www.buymeacoffee.com/bugbounty<br>☕☕☕☕☕

**Comment by jolle** [comment]
The MongoDB instance has been removed for a while, it doesn't actually exist.
